name: Generate History Short

on:
  workflow_dispatch:

jobs:
  history:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install google-genai

      - name: Generate History topic
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python history_generator.py

      - name: Check generated history database
        run: |
          echo "===== HISTORY DATABASE ====="
          cat history_data/previous_topics.json
          echo "===== GIT STATUS ====="
          git status

      - name: Save topic history
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f history_data/previous_topics.json

          echo "===== CHANGES TO COMMIT ====="
          git diff --cached

          git commit -m "Update history topic database" || echo "Nothing to commit"

          git pull --rebase origin ${GITHUB_REF_NAME}

          git push origin HEAD:${GITHUB_REF_NAME}

      - name: Upload generated History data
        uses: actions/upload-artifact@v4
        with:
          name: history-output
          path: history_output/
