name: Generate History Short

on:
  workflow_dispatch:

jobs:
  history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install google-genai

      - name: Generate History topic
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python history_generator.py

      - name: Upload generated History data
        uses: actions/upload-artifact@v4
        with:
          name: history-output
          path: history_output/
